services:
  vattenkraft-scraper:
    image: vattenkraft-scraper:latest
    container_name: vattenkraft-scraper
    restart: always
    ports:
      - "3080:3080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/api/v1/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
